version: "3"

services:
  learnapi:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./learnapi:/learnapi

    command: >
      sh -c " python manage.py runserver 0.0.0.0:8000"
